spring:
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  http:
      encoding:
         charset : UTF-8
         enabled : true
         force : true
  
  
  h2:
    console:
      enabled: true
      path: /h2
      
      
  
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    data-password:
    initialization-mode: always
    data: classpath:db/Store_dml.sql
server:
  port: 8182
  
 