spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://database-msa-guild-postgre.cdnxkpguqzfr.ap-northeast-2.rds.amazonaws.com:5432/svcPrj
    username: msaguild
    password: msaguild
    driverClassName: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
        #show-sql: true
    properties:
      hibernate:
        format_sql: true 
server:
  port: 8182
  
 